tobiasehlert/teslamateapi

src/v1_TeslaMateAPICarsStatus.go
src/webserver.go

Previously a connection we made to the MQTT broker whenever a status API request was made. This was problematic because multiple requests could end up being processed simultaneously (and the code was not thread safe). This pull refactors things so a connection with the broker is established once and status updates are cached.

Refactor MQTT so it connects once to broker and caches messages 

---

src/v1_TeslaMateAPICarsDrives.go

Already implemented in DriveDetails, logic was duplicated exactly in this pull request

Convert SpeedMax and SpeedAvg in Drive (km->mi)

---

src/v1_TeslaMateAPICarsCharges.go

*Expected*
The Charges endpoint should still return data, even if a portion of charges have corrupted data.
*How it happens*
Charges can become corrupted if Teslamate does not detect that a charge ever ended, such as if the car or Teslamate goes offline when the charging ends.
*Note*
The charging_processes table's most recent row may be missing an end_date if the charge is in progress. These charges were already being skipped in the chargingDetails endpoint. I am assuming it is safe to skip them here, since they essentially have no data until the charge finishes.
*Please Test*
- Please test that this still builds as I am not entirely familiar with Go and am unsure how to test this on my docker container.

Skip Malformed Rows (those missing an end_date)

---

src/v1_TeslaMateAPICarsChargesDetails.go

Following up on https://github.com/tobiasehlert/teslamateapi/issues/43
*Reason*
A detailed charge is malformed if the end_date is missing in SQL. It's also possible a charge that is in progress will be missing this value as well, in which case this detailed charge isn't populated with data.
*Better Solutions* (long term)
Adjust error handling across the API:
- *Opt 1:* Instead of `ValidResponse` being a boolean, replace with `ResponseError`. Change the if statement at the bottom of each file to check for the `ResponseError`'s existence instead of `if ValidResponse {...} else {...}`. Remove all log.Fatal(err) so that the API can still return responses gracefully, and set status to 200 OK since the response will still technically be HTTP valid. Break execution of further steps and return …

Prevent fatal error when detailed charge malformed

---

src/v1_TeslaMateAPICarsCharges.go
src/v1_TeslaMateAPICarsDrives.go
src/v1_TeslaMateAPICarsUpdates.go

API should fail gracefully if an empty response is sent. This was completed against Charges, Drives, and Updates API endpoints.
Example reason: an API consumer should be able to traverse the pages until empty data is returned.
Note: A generic error will be thrown if the data set is empty (including on a fresh install of TeslaMate) or if there is an invalid charge in the response (in the case of charges). Therefore, it's impossible to know if all data points were traversed or if an error exists on a single object in the array (See: #43 for Charges bug)

Update Charges, Drives, and Updates API to Allow Empty Responses as Valid

---

src/v1_TeslaMateAPICarsCharges.go
src/webserver.go

Only added surface level implementation to one place as a proof of concept. Theoretically, we would sprinkle `TeslaMateAPIHandleErrorResponse` across the endpoint files instead of waiting until the end. Then we can forget `ValidResponse` entirely, and know that it is successful if we reach the bottom.
The final goal here it to remove instances of log.Fatal(err) where the app can no longer handle an error response. When it crashes, the connection is dropped and the user isn't provided an error. This lays the foundation to fix it.
----
This is not ready for a merge, but I want to get discussion about it going. It's a proof of concept. Also I don't have enough time tonight to put together a 100% implementation.

PoC of response handler

---

src/CommandSupport.go

Per discussion on the [timdorr/tesla-api](https://github.com/timdorr/tesla-api/discussions/455) repo.
This accepts a `charging_amps` parameter.
As far as I can tell, this is the only place a change is required, but let me know if something further is needed.

Add support for `set_charging_amps` command

---

README.md
src/CommandSupport.go

Added commands:
- /command/set_charging_amps (#112)
- /command/set_scheduled_charging
- /command/set_bioweapon_mode
- /command/set_scheduled_departure
- /command/navigation_sc_request
- /command/upcoming_calendar_entries
- /command/dashcam_save_clip
Removed commands:
- /command/charge_standard
- /command/charge_max_range
Added commands section:
- COMMANDS_UNKNOWN
Updating commands based on [timdorr/tesla-api endpoints.md](https://github.com/timdorr/tesla-api/blob/9d4345631109603ff2770412e8786ac98d033bd5/docs/miscellaneous/endpoints.md) file for version _4.2.2_.

Add support for new endpoints

---

src/v1_TeslaMateAPICars.go
src/v1_TeslaMateAPICarsCharges.go
src/v1_TeslaMateAPICarsChargesDetails.go
src/v1_TeslaMateAPICarsCommand.go
src/v1_TeslaMateAPICarsDrives.go
src/v1_TeslaMateAPICarsDrivesDetails.go
src/v1_TeslaMateAPICarsLogging.go
src/v1_TeslaMateAPICarsStatus.go
src/v1_TeslaMateAPICarsUpdates.go
src/v1_TeslaMateAPIGlobalsettings.go
src/webserver.go

Better response handler for TeslaMateApi.
Two functions that are supposed to be used from all enpoints for a "same" way of handling responses:
- TeslaMateAPIHandleErrorResponse
- TeslaMateAPIHandleOtherResponse
- TeslaMateAPIHandleSuccessResponse
Linked issue:
- resolves #77
Related PRs:
- #76
- #79

Feature: response handler

---

src/CommandSupport.go

Expected JSON:
```json
{"enabled_commands":["/logging/resume","/logging/suspend","/command/honk_horn","/command/flash_lights"]}
```
Actual JSON:
```json
{"enabled_commands":["/logging/resume /logging/suspend","/command/honk_horn /command/flash_lights"]}
```
Issue appeared after #132.

Fix append of commands to allowList

---

go.mod
go.sum
src/webserver.go

JSON is highly compressible, so size of response decreases a lot with this.

adding gzip compression

---

src/webserver.go

Returning proper 404 and also a JSON-formatted error response.

adding 404 for not found endpoints

---

src/webserver.go

Gin is not removed when forwarding requests to upstream destinations.
Therefore disabling the proxy functionality to remove warning logged to console.

disabling proxy feature of gin

---

src/CommandSupport.go
src/EncryptionSupport.go
src/v1_TeslaMateAPICarsCommand.go

Adds support for AES_256_GCM encrypted API tokens implemented by PR https://github.com/adriankumpf/teslamate/pull/2360 in TeslaMate.

TeslaMate encryption of API tokens

---

go.sum
src/EncryptionSupport.go
src/v1_TeslaMateAPICarsCommand.go

This is mostly based on TeslaMate: https://github.com/adriankumpf/teslamate/blob/f91f8d58140a4e151ee492a03b483799c63ed7aa/lib/tesla_api/vehicle.ex#L27 
Tesla China uses different API endpoint, this PR resolve "iss" field from access_token.
Global region are not affected.

Support execute commands for China region cars 

---

.github/workflows/build.yml

Removing the leading **v** in container image tag so that it's correct [semver](https://semver.org) versioning.
This means that users that are using a specific version in their docker-compose (or other) need to remove the leading **v**.
For the upcoming version _1.15_ the tag would change from `v1.15` to `1.15`, looking like this in the docker-compose file:
```yaml
image: ghcr.io/tobiasehlert/teslamateapi:1.15
```

Removing **v** in container image tag

---

src/v1_TeslaMateAPICars.go
src/v1_TeslaMateAPICarsCharges.go
src/v1_TeslaMateAPICarsChargesDetails.go
src/v1_TeslaMateAPICarsDrives.go
src/v1_TeslaMateAPICarsDrivesDetails.go
src/v1_TeslaMateAPICarsStatus.go
src/v1_TeslaMateAPICarsUpdates.go

fixed new installations that don't have a name of their cars set yet.

change CarName to be NullString instead of string

---

src/CommandSupport.go

Added commands:
- /command/set_cop_temp
- /command/set_cabin_overheat_protection
- /command/remote_auto_steering_wheel_heat_climate_request (_\*missing documentation_)
- /command/remote_steering_wheel_heat_level_request (_\*missing documentation_)
- /command/adjust_volume
- /command/remote_boombox
- /command/get_active_route
- /command/get_managed_charging_sites
- /command/add_managed_charging_site
- /command/remove_managed_charging_site
- /command/update_charge_on_solar_feature
- /command/get_charge_on_solar_feature
- /command/take_drivenote
- /command/navigation_gps_request
Moved command:
- /command/navigation_sc_request
Note:
\* Even though marked commands are missing documentation on https://github.com/timdorr/tesla-api, they are placed under climate section based on naming.
Updating …

alignment of commands to version 4.23.6

---

Dockerfile

This addresses issue with container being run with `nonroot` that results in permission denied.
fix #273

Fix permission issues with Dockerfile nonroot implementation

---

src/v1_TeslaMateAPICarsStatus.go

Since we already have latitude and longitude data in our CarGeodata struct, I don't see us using the combined value in the end. So we'll stick with only adding an case-entry for `location` and we don't get the current errors anymore.
fix #277

fix: issue reported after location mqtt implementation

---

README.md
src/v1_TeslaMateAPICarsStatus.go
src/webserver.go

Adds two new endpoints to application so that kubernetes can monitor it.
- GET `/api/healthz`
- GET `/api/readyz`
fix #190

Feature: adding support for k8s health endpoints

---

src/webserver.go

error message when starting container:
```log
teslamate-teslamateapi-1 | panic: runtime error: invalid memory address or nil pointer dereference
teslamate-teslamateapi-1 | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x47178e]
teslamate-teslamateapi-1 | 
teslamate-teslamateapi-1 | goroutine 1 [running]:
teslamate-teslamateapi-1 | sync/atomic.(*Value).Store(0x0, {0x8143c0, 0xbf6b68})
teslamate-teslamateapi-1 | 	/usr/local/go/src/sync/atomic/value.go:54 +0x2e
teslamate-teslamateapi-1 | main.startMQTT()
teslamate-teslamateapi-1 | 	/go/src/v1_TeslaMateAPICarsStatus.go:195 +0x857
teslamate-teslamateapi-1 | main.main()
teslamate-teslamateapi-1 | 	/go/src/webserver.go:67 +0x23b
```
rel #191

fix: invalid memory address or nil pointer dereference

---

src/v1_TeslaMateAPICarsStatus.go

Adds a line to convert the current speed from KPH to MPH if the unit is "mi". 
Issue #300

Converts the current speed if unit is "mi"

---

src/v1_TeslaMateAPICarsStatus.go
src/webserver.go

Error introduced in #299, where `MQTTInformationData.DrivingDetails.Speed` is in float64 format and not int.
Built [10348246519](https://github.com/tobiasehlert/teslamateapi/actions/runs/10348246519) failed, but this PR fixes issue.
rel #299

fix: status drivingdetails.speed to be int and not float64

---

README.md
src/v1_TeslaMateAPICarsCommand.go
src/webserver.go

As already discussed #255 #292 the official Tesla API will be the only way to send commands.
Using third-party Tesla API providers (or a self-hosted commands proxy) would allow command endpoints to be preserved.
I added an environment variable to allow users to choose their API provider.

Ability to use custom API endpoint

---

src/v1_TeslaMateAPICarsCharges.go
src/v1_TeslaMateAPICarsChargesDetails.go

Feature to show latitude and longitude in charge details.
- Added latitude and longitude fields to charge data in the API response
- Values are sourced from the position table in the database
- No unit conversion is applied to coordinates (they remain in decimal degrees)

feat: add latitude and longitude to charges

---

README.md
src/v1_TeslaMateAPICarsCharges.go
src/v1_TeslaMateAPICarsDrives.go
src/webserver.go

This PR adds support for `startDate` and `endDate` in the following endpoints:
```url
api/v1/cars/1/charges
api/v1/cars/1/drives
```
use it like this:
```url
api/v1/cars/1/drives?startDate=2025-06-20T21:10:27+02:00&endDate=2025-06-22T21:10:27+02:00
api/v1/cars/1/charges?startDate=2025-06-20T17:37:48+02:00
```

feat: add support for filtering on start and end date

---

Dockerfile

When in Kubernetes another user is set (via `runAsUser`), such as `65534`, the binary fails to start because other doesn't have the execute flag on the `app` binary.
This PR fixes it.

fix(docker): adjust chmod permissions on binary

---

.github/workflows/build.yml
.github/workflows/codeql-analysis.yml

This pull request refactors the `.github/workflows/build.yml` workflow to improve multi-architecture Docker image builds, enhance security, and streamline provenance and signing processes. The workflow is split into per-architecture and manifest jobs, with better handling of image digests, attestations, and signatures. Key changes include matrix-based builds, artifact handling for digests, and more robust provenance and signature verification.
**Multi-architecture build and workflow improvements:**
* The `build` job now uses a matrix strategy to build images for `linux/amd64`, `linux/arm64`, and `linux/arm/v7` on appropriate runners, replacing the previous single-job approach. This enables parallel and more reliable builds for each architecture. (`.github/workflows/build.yml`)
* Added a …

feat(ci): use multiple runners for build

---

.github/workflows/build.yml

This pull request makes a minor update to the GitHub Actions workflow by changing how the DockerHub username is referenced. The workflow now uses GitHub Actions variables instead of secrets for the DockerHub username in all relevant steps.
rel #362

fix(ci): use dockerhub variable instead

---

src/webserver.go

This pull request refactors the string conversion helper functions in `src/webserver.go` to improve error handling and logging. The changes make the behavior of these functions clearer and ensure that warnings are only logged in debug mode, reducing unnecessary log noise in production.
Also making a log entry only if the application is set to debug-mode, which prevents unwanted errors like reported in #322.
Close #322

chore: rewrite logic of convertStringTo-functions
