tobiasehlert/teslamateapi

README.md
port directive should be ports
=> Update README.md to fix docker-compose file example

src/v1_TeslaMateAPICarsCommand.go, src/webserver.go
Addresses https://github.com/tobiasehlert/teslamateapi/issues/6
=> proxy commands to Tesla API

src/V1_TeslaMateAPICarsChargesDetails.go
https://golang.org/pkg/database/sql/#NullBool
https://github.com/tobiasehlert/teslamateapi/issues/18
=> handle Null -> Bool

src/CommandSupport.go
=> enable and defer

README.md, src/CommandSupport.go, src/v1_TeslaMateAPICarsLoggingCommand.go, src/webserver.go
=> add support for teslamate logging resume/suspend

src/v1_TeslaMateAPICarsCharges.go
Reverts tobiasehlert/teslamateapi#40
=> Revert "Update v1_TeslaMateAPICarsCharges.go"

README.md, src/v1_TeslaMateAPICarsLogging.go, src/webserver.go
I broke apart the Teslmate URL and renamed the function/file. 
The code is still a little W.E.T.  -- I will see about refactoring it as time allows this week.
=> teslamate logging feature updates

.github/workflows/build.yml, CHANGELOG.md, src/webserver.go
Feature to pass TeslaMate PUT requests to TeslaMate from TeslaMateApi
closes #10
=> Feature 10 logging commands

src/v1_TeslaMateAPICarsCharges.go, src/v1_TeslaMateAPICarsChargesDetails.go
adds filter in SQL query to exclude charges where end_date is null.
rel #43, #68
=> Remove charges and drives that have null on end_date

README.md, src/AuthSupport.go, src/webserver.go
=> allow command auth disable via API_TOKEN_DISABLE

src/v1_TeslaMateAPICarsStatus.go
I couldn't figure out how to comment on an open branch without a pull request, so I opened this. Very excited to see the new `power` MQTT value pulled in. Is there a reason it wasn't merged?
=> adding of MQTT power int

src/webserver.go
I see this error frequently, it would be nice to see why it's occuring
=> Provide better error details

src/v1_TeslaMateAPICars.go
- changing float64 to NullFloat64 on efficiency
fix #128
=> Bug: changing float64 to NullFloat64 on efficiency

.github/workflows/build.yml
- adding edge docker image tag for image based on main branch
- adding GHCR to container repos for future builds
- updating build apiVersion during build with version tag
- only doing build when certain paths are changed
=> Updating build workflow with enhancements

src/webserver.go
We should not require it, but it's probably nicer to shutdown gin instead of killing it =P
=> adding graceful shutdown to gin

src/v1_TeslaMateAPICarsStatus.go
adding two new fields in status endpoint:
- `charge_current_request`
- `charge_current_request_max`
Implements #140
Needs https://github.com/adriankumpf/teslamate/discussions/2412
=> Feature: adding two new fields in status endpoint

src/v1_TeslaMateAPICarsStatus.go
Extends status endpoint with TPMS metrics for wheels.
rel: https://github.com/adriankumpf/teslamate/pull/2706
=> Add support for tire pressure metrics from MQTT

src/CommandSupport.go
- /command/charge_standard
- /command/charge_max_range
- /command/remote_seat_cooler_request
- /command/set_climate_keeper_mode
- /command/remote_auto_seat_climate_request
=> add support for new commands

Dockerfile
which should shorten build time..
=> updating `go build` step in dockerfile

src/NullSupport.go, src/v1_TeslaMateAPICars.go, src/v1_TeslaMateAPICarsCharges.go, src/v1_TeslaMateAPICarsChargesDetails.go, src/v1_TeslaMateAPICarsDrives.go, src/v1_TeslaMateAPICarsDrivesDetails.go, src/v1_TeslaMateAPICarsUpdates.go
- Added AddressDetails (start and end address) with all data from Teslamate on /drives and /drives/#id/details
- Changed string to nullstring for carName, I had the error on every new car (no name is set at delivery).
- Replaced NullString support as it didn't work (Value and Valid attributes were marshalled)
=> adding address details

src/NullSupport.go
=> fix NullString issue in several endpoints

Dockerfile
- using alpine specific version instead of latest
- running container with nonroot user
=> update Dockerfile to specific version and use of nonroot user

Dockerfile
=> fix Dockerfile alpine container typo

src/v1_TeslaMateAPICarsStatus.go
- add support for tire pressure warning from MQTT
rel: https://github.com/teslamate-org/teslamate/pull/3424
- add support for navigation active route drive state from MQTT
rel: https://github.com/teslamate-org/teslamate/pull/3657
=> Add tire pressure warning and active route from mqtt

.github/workflows/build.yml
=> add cosign of images in build workflow

src/webserver.go
=> fix: resolving fatal when disabling of mqtt

src/v1_TeslaMateAPICarsStatus.go, src/webserver.go
- adding new MQTT topics to status endpoint
- updating existing topics with other handling
- updating pressure to be shown in preferred format
_note: adjusted to TeslaMate v1.29.2_
=> Add and update of MQTT topics

src/v1_TeslaMateAPICarsStatus.go
rel: https://github.com/teslamate-org/teslamate/pull/3813
=> add center_display_state mqtt topic

Dockerfile
- Reduce the amount of consecutive RUN instructions [docker:S7031](https://sonarcloud.io/organizations/tobiasehlert/rules?open=docker%3AS7031&rule_key=docker%3AS7031)
- Too long RUN instruction should be split into multiple lines [docker:S7020](https://sonarcloud.io/organizations/tobiasehlert/rules?open=docker%3AS7020&rule_key=docker%3AS7020)
_Suggestions by SonarCloud_
=> decrease Dockerfile layers

src/v1_TeslaMateAPICarsCharges.go, src/v1_TeslaMateAPICarsChargesDetails.go
=> feat: add odometer information to charge-endpoints

src/v1_TeslaMateAPICarsCharges.go, src/v1_TeslaMateAPICarsChargesDetails.go
=> fix: incorrect 0 values from charge_energy_used charges queries
